### PR TITLE
Add Websockets SSL support

### PR DESCRIPTION
**Pull request by tenchman**
Tested with Chrome/Opera/Firefox5 on Linux and IE9 on Windows7.

### CODE REVIEW

**Comment by kanaka** [comment]
@tenchman, I applied your pull request. The changes look good. I've applied one additional patch to your changes to add sslkeyfile and sslcertfile options to the command line, and also to enable SSL support in the configure script even when x11vnc is not requested that way anything linked with libvncserver will have the SSL support (not just x11vnc).

If you're interested in pushing these changes towards the upstream libvncserver (I don't have the time myself at the moment to drive that effort), you might consider using the existing -ssl file option, but making it apply to the websockets mode as well. I suspect the upstream maintainer(s) won't necessarily want separate options for the WebSockets mode.

**Comment by tenchman** [comment]
OK, here we go. I've adapted the changes to the new CMake based build system too. The autotools system seems to be completely broken.

https://sourceforge.net/tracker/?func=detail&aid=3363941&group_id=32584&atid=405860

**Comment by kanaka** [comment]
BTW, one current caveat with the current tree is that non-true color mode is only partially implemented for tightPNG. If you are willing to tackle it, I can point you to the equivalent working code in QEMU.

**Comment by tenchman** [comment]
Hi,

there is actually a discussion on the libvncserver mailinglist. Maybe is't a good idea if you can explain some things there.
https://sourceforge.net/mailarchive/forum.php?forum_name=libvncserver-common&max_rows=25&style=threaded&viewmonth=201107

**Comment by kanaka** [comment]
Hmm, I signed up to the list a couple days ago and haven't gotten any messages. I'll try with digest off and see if that helps. However, I've read the discussion on the archives and it sounds like it's going well.

Is there something in particular you wanted me to comment on? It looks like you're doing just as good (or better job) than I would. :-)

BTW, one of the things that is going to happen in the next couple of months is that the next major revision of the WebSockets protocol is going to be shipped in new browser releases. Right now libvncserver supports browsers using Hixie-75 aned Hixie-76. Browsers are soon going to start supporting HyBi-10 (or later). The IETF/HyBi versions of the protocol address the security concern that prevents Firefox and Opera from shipping with native WebSockets turned on by default. So before the end of the year Chrome, Firefox, Safari and Opera (and possibly even Microsoft) will likely all release browsers with WebSockets enabled by default and supporting the new protocol.

I may get around to adding that to libvncserver but probably not for a while. If you want to tackle it, you can refer to the python version of websockify (https://github.com/kanaka/websockify) which supports Hixie-75, Hixie-76, and HyBi-7, 8, 9. Also, I made a branch of web-socket-js that has the client side support for HyBi-07: https://github.com/gimite/web-socket-js/tree/hybi-07

**Comment by kanaka** [comment]
One other thing I forgot to mention. The UTF8 encoding is going away (really, it has gone away since noVNC hasn't supported it for a while). It was more of an experiment to try and figure out a slightly more bandwidth efficient way to encode binary data than base64.

Along with the new revision of the WebSockets protocol is an update to the WebSocket API to add binary support (since the new protocol can mark frames as binary instead of UTF-8). The binary support in the API and protocol will mean that no encoding will be necessary to send binary data. The base64 support will be needed for a while to support older browser versiosn, but eventually (several years) it will be dropped too in favor of just using the built-in binary support.

So the UTF-8 encoding support in libvncserver should really be excised.

**Comment by tenchman** [comment]
Hi,

some things happened in the meantime as you may already noticed. I've
reworked your changes to libvncserver, added encryption support per
openssl/gnutls and sent them to upstream. So chances are good to see
websockets support in the next release of libvncserver.

On Mon, 18 Jul 2011 08:58:29 -0700
kanaka
reply@reply.github.com
wrote:

> Hmm, I signed up to the list a couple days ago and haven't gotten any
> messages. I'll try with digest off and see if that helps. However, I've
> read the discussion on the archives and it sounds like it's going well.

Yeah, more or less, :-)

> Is there something in particular you wanted me to comment on? It looks like
> you're doing just as good (or better job) than I would. :-)

The unbelievable happened. Firefox 6 seems to ship with a newer version of the
websockets protocol. Since I'm not the biggest websockets expert, it
would be fine if you could me point to the right direction. What are the
major changes to the protocol?

> BTW, one of the things that is going to happen in the next couple of months
> is that the next major revision of the WebSockets protocol is going to be
> shipped in new browser releases. Right now libvncserver supports browsers
> using Hixie-75 aned Hixie-76. Browsers are soon going to start supporting
> HyBi-10 (or later). The IETF/HyBi versions of the protocol address the
> security concern that prevents Firefox and Opera from shipping with native
> WebSockets turned on by default. So before the end of the year Chrome,
> Firefox, Safari and Opera (and possibly even Microsoft) will likely all
> release browsers with WebSockets enabled by default and supporting the new
> protocol.

As mentioned above, exactly this happened with the newest firefox.

> I may get around to adding that to libvncserver but probably not for a
> while. If you want to tackle it, you can refer to the python version of
> websockify (https://github.com/kanaka/websockify) which supports Hixie-75,
> Hixie-76, and HyBi-7, 8, 9. Also, I made a branch of web-socket-js that has
> the client side support for HyBi-07:
> https://github.com/gimite/web-socket-js/tree/hybi-07

I will try my best, but I'm only a slave of my employer too. :-) That said,
the time i'll have to play with it is limited.

Cheers,

## Gernot

Mahatma Glück, Mahatma Pech, Mahatma Gandhi.
    -- indian proverb

**Comment by kanaka** [comment]
Gernot,

Sorry for the slow reply. I was at LinuxCon last week and didn't have many free opportunities.

The protocol changes shouldn't be too bad. The specification is here: http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-10
- The handshake has changed somewhat (simpler actually). The header names have changed somewhat. The weird md5 hashing algorithm has been dropped. In its place is a simpler SHA1 based accept hash that is done using handshake headers instead of in the first bits of frame data.
- Rather than using the '\x00' prefix and '\xff' postfix to delineate frame boundaries, the new protocol uses a frame header that has the length of the frame in the header.
- Finally, all data from the client (browser) to the server is hashed using a 4-byte mask key. The good thing is that every frame has the hash key in the frame header (so no state to remember) and the unhashed data is the same length as the hashed data so there is no buffer copy needed.

If you look at the encode_hybi and decode_hybi routines in websockify you can see how I do it in the python implementation.

I might find some time to work on this myself. Hopefully it will be before firefox 6 and Chrome 14 go stable, but no guarantees. :-(

**Comment by tenchman** [comment]
As you may have noticed i've pushed initial hybi support to my libvncserver/websockets branch. Maybe you have some free minutes to review and comment it. If all goes well, i could port it websockify's c implementation too.

**Comment by kanaka** [comment]
Yep, I saw it. I've made a few updates and pushed to this branch: https://github.com/kanaka/libvncserver/tree/websockets

I've also tested it and it seems to work well with both Hixie and HyBi clients.
- Removed the experimental UTF-8 encoding.
- Added sha1.\* code from IETF so that we don't need openssl to be present (build was breaking for me too).
- Use the protocol field in the handshake to determine whether to use base64 encoding or not (if 'binary' is specified in the protocol then do not base64 encode). Unfortunately, since the client doesn't speak first in VNC protocol, we can't determine from the first frame whether the client is capable of binary data transfer or not :-(.

Also, I've added you as a collaborator to my kanaka/libvncserver project. You can continue to use your fork and we can pull back and forth or you can do changes right there if you want.

Yeah, if you want to update/maintain the C implementation of websockify that would be fine with me. My main priority is the full featured python version. The other version have been for example and learning, but if you want to keep the C version up to date and synchronized that would be great (it would probably be a while before I got around to adding HyBi support to it anyways).

Thanks

**Comment by tenchman** [comment]
I've pushed my current version to your websockets branch. Thank you for the write access. Unfortunately i've pushed the non-rebased local branch. Sorry for that, but it is in sync with my rebased version. I've tested it on fedora 32bit and 64bit with openssl and gnutls as well. Funnily enough, on my **64bit** Fedora15 with Firefox6 I had to prefix "WebSocket" with "Moz" in noVNC to get native Websockets support, whereas on my **32bit** Fedora15 with Firefox6 it works without prefixing. Just for the records...

**Comment by kanaka** [comment]
No problem about the push.

Supposedly all versions of Firefox 6 are supposed to have WebSocket prefix with "Moz". I argued against it in the bug since it's attempting to cover the protocol rather than just an intermediate API and also since Chrome is not prefixing it. But, clearly, I didn't win that argument.

**Comment by bk138** [comment]
hi guys, whats the current status of websockets for libvncserver? any open issues? i would like to merge this to master and get out the next release soonish. 

ps: which branch to merge, which one is the most up to date? you can of course also send patches to the libvnc mailing list.

cheers,
   christian

**Comment by kanaka** [comment]
Christian. I think it's in pretty good shape. I just merged in @tenchman's latest change to the 'websockets' branch at https://github.com/kanaka/libvncserver. I haven't tested that change yet so I'll let Gernot weigh in on whether he has tested that change adequately.

Really the other remaining issue I know of is that the tightPNG code in that branch doesn't properly support indexed color mode (i..e color mapped): https://github.com/kanaka/libvncserver/issues/3 I don't think this is a blocking issue since very few clients except noVNC seem to even be able to request indexed (non-truecolor) mode. Just a couple of days ago @KarimAllah expressed interest in adding that support.

So unless @tenchman thinks the most recent change (combining send/receive encode/decode buffer) needs more testing, or unless you think the tightPNG indexed mode needs to be worked in, I think it's probably ready to go.

**Comment by bk138** [comment]
Joel Martin reply@reply.github.com schrieb:

> Christian. I think it's in pretty good shape. I just merged in
> @tenchman's latest change to the 'websockets' branch at
> https://github.com/kanaka/libvncserver. I haven't tested that change
> yet so I'll let Gernot weigh in on whether he has tested that change
> adequately.
> 
> Really the other remaining issue I know of is that the tightPNG code in
> that branch doesn't properly support indexed color mode (i..e color
> mapped): https://github.com/kanaka/libvncserver/issues/3 I don't think
> this is a blocking issue since very few clients except noVNC seem to
> even be able to request indexed (non-truecolor) mode. Just a couple of
> days ago @KarimAllah expressed interest in adding that support.
> 
> So unless @tenchman thinks the most recent change (combining
> send/receive encode/decode buffer) needs more testing, or unless you
> think the tightPNG indexed mode needs to be worked in, I think it's
> probably ready to go.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kanaka/libvncserver/pull/2#issuecomment-2039232

Sounds good! There was one issue with binary mode that you mentioned iirc? Didn't fully understand that one though :-)

**Comment by kanaka** [comment]
I think the binary support is complete (although I'm sure we'll find bugs once browsers actually begin supporting this), it's just non-optimal due to the VNC server "speaking" first so we have to negotiate binary support using the protocol field in the WebSocket handshake (because otherwise at the point we receive and send the first VNC server message we don't know whether the browser supports binary messages yet or not).

**Comment by bk138** [comment]
well sounds ok as long as this form of negotiation works. i'll pull your branch once i'm back from vacation... ah and sorry for the unnecessary citation junk above :-)

**Comment by kanaka** [comment]
bk138: yep, it should work. There isn't really a way to test it thoroughly until a browser or two is released with binary support. Hovever binary mode is simpler than base64 (just pass the data directly), so any problems will probably be in the handshake mechanism on the client side.

More about how it works:

In the WebSocket handshake is a protocol header which can be set by the client (based on what the client supports) to multiple values. The server then sends back the chosen protocol (one value) in the protocol field in the handshake response with the protocol that was selected so the client knows which one to use.

noVNC will detect that the browser supports WebSocket binary messages and set the protocol field to "binary, base64" (otherwise it will just send "base64"). The server will respond with "binary" (or "base64" if the client did not specify "binary" as an option).

**Comment by tenchman** [comment]
Hi,

sorry for the late response. I was busy doing other things @ work last days.... Currently i'm happy with the code although there is much room for improvements. Especially when using Websockets with binary encoding, one could avoid useless memcpy's by using writev() for instance. But this needs a lot of work on libvncserver in genera,l so this should be scheduled for a later release.

**Comment by dscho** [comment]
Please note that @kanaka is not a maintainer of LibVNCServer I just added an official GitHub repository for the project: https://github.com/LibVNC/libvncserver. Please consider opening the pull request there.

**Pull request merged**
